name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
